server.port=${SERVER_PORT:3000}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost/evernet}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}
evernet.jwt.secret.key=${EVERNET_JWT_SECRET_KEY:jwt.secret.jwt.secret.jwt.secret.jwt.secret.jwt.secret.jwt.secret}
spring.jackson.serialization.indent_output=true
